<?xml version="1.0" encoding="UTF-8"?>
<!-- Service -->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:xs="http://www.w3.org/2001/XMLSchema"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:ns="http://schemas.xmlsoap.org/soap/encoding/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:osci="http://www.osci.de/2006/07/wsdl/"
             xmlns:tpl="http://www.dvdv.de/dvdv/template/"
             xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
             xmlns:tns="http://www.xleitstelle.de/xbau/2/5/XBau25-ABK-BAB2AIKsync.wsdl"
             xmlns:xbau="http://www.xleitstelle.de/xbau/2/5"
             xmlns:xbauk="http://www.xleitstelle.de/xbau/kernmodul/1/2/2"
             name="XBau25-ABK-BAB2AIKsync"
             targetNamespace="http://www.xleitstelle.de/xbau/2/5/XBau25-ABK-BAB2AIKsync.wsdl"
             xsi:schemaLocation="http://schemas.xmlsoap.org/wsdl/ http://schemas.xmlsoap.org/wsdl/">
   <documentation>
      <tpl:categories>
         <tpl:category>Architekten- und Ingenieurkammer</tpl:category>
      </tpl:categories><![CDATA[<html><head>
<title>Datenübermittlungen zwischen den Architekten- und Ingenieurkammern und den Bauaufsichtsbehörden im Rahmen des Nachweises der Bauvorlageberechtigung</title>
</head>
<body>
<p>Folgende Nachrichten des XBau-Schemas sind als Input der Operation 
<i>sendeABK-BAB2AIKsync</i> zulässig:<ul>
            <li>kammernverzeichnis.anfrage.0930</li>
         </ul></p>
<p>Folgende Nachrichten des XBau-Schemas sind als Output der Operation
<i>sendeABK-BAB2AIKsync</i> zulässig:<ul>
            <li>kammernverzeichnis.auskunft.0931</li>
         </ul></p>
<p>Folgende Nachrichten des XBau-Schemas sind als Fehlermeldung der einzigen Operation
<i>sendeABK-BAB2AIKsync</i> zulässig:<ul>
            <li>prozessnachrichten.rueckweisung.G2G.1100</li>
         </ul></p>
<p>Organisationsschlüssel für <i>find.servicedescription</i>-Anfragen sind die entsprechende Codes der unter der XBau-Spezifikation veröffentlichten Codeliste urn:xoev-de:xbau:codeliste:kammer; der zu verwendende Präfix lautet "<b>aik</b>". 
Zulässige Dienstanbieter und -nutzer sind die Architekten- und Ingenieurkammern (DVDV-Organisationskategorie <b>„Architekten- und Ingenieurkammer“</b>).
Zulässige Dienstnutzer sind ausschließlich Organisationen in der DVDV-Organisationskategorie <b>"Bauaufsichtsbehörde"</b>.</p>
</body></html>]]></documentation>
   <import namespace="http://www.osci.de/2006/07/wsdl/"
           location="http://www.osci.de/wsdl-osci-binding/WSDL-OSCI-Binding_1.2.xsd"/>
   <import namespace="http://www.xleitstelle.de/xbau/2/5"
           location="https://xleitstelle.de/xbau/schema/2/5/xbau-nachrichten-kammernverzeichnis.xsd"/>
   <import namespace="http://www.xleitstelle.de/xbau/kernmodul/1/2/2"
           location="https://xleitstelle.de/xbau/schema/kernmodul/1/2/2/xbau-kernmodul-prozessnachrichten.xsd"/>
   <message name="abk-bab2aiksyncRequestNachricht">
      <part name="request" element="xbau:kammernverzeichnis.anfrage.0930"/>
      <part name="optionaleNachricht" type="xs:anyType"/>
   </message>
   <message name="abk-bab2aiksyncResponseNachricht">
      <part name="response" element="xbau:kammernverzeichnis.auskunft.0931"/>
      <part name="optionaleNachricht" type="xs:anyType"/>
   </message>
   <message name="abk-bab2aiksyncFaultNachricht">
      <part name="fault" element="xbauk:prozessnachrichten.rueckweisung.G2G.1100"/>
      <part name="optionaleNachricht" type="xs:anyType"/>
   </message>
   <portType name="osciABK-BAB2AIKsyncInterface">
      <operation name="sendeABK-BAB2AIKsync">
         <input message="tns:abk-bab2aiksyncRequestNachricht"/>
         <output message="tns:abk-bab2aiksyncResponseNachricht"/>
         <fault name="faultMessage" message="tns:abk-bab2aiksyncFaultNachricht"/>
      </operation>
   </portType>
   <binding name="osciBinding" type="tns:osciABK-BAB2AIKsyncInterface">
      <osci:binding signatureLevel="none" encrypted="true">
         <osci:reader name="Inhaltsdaten-Verschlüsselungszertifikat">
            <tpl:certificate/>
         </osci:reader>
         <osci:author name="Inhaltsdaten-Signaturzertifikat">
            <tpl:certificate/>
         </osci:author>
      </osci:binding>
      <!-- Vorbelegung der Richtlinien zur Signatur und Verschlüsselung der Nutzdaten für alle Operationen -->
      <operation name="sendeABK-BAB2AIKsync">
         <osci:operation communicationType="request-response" subject="XBAU_DATA"/>
         <input>
            <osci:container signatureLevel="advanced"
                            encrypted="true"
                            name="XBAU_DATA"
                            required="true">
               <osci:readerRef ref="Inhaltsdaten-Verschlüsselungszertifikat"/>
               <osci:part>
                  <osci:content part="tns:request"/>
               </osci:part>
            </osci:container>
            <osci:container signatureLevel="none" encrypted="false" required="false">
               <osci:part>
                  <osci:content part="tns:optionaleNachricht"/>
               </osci:part>
            </osci:container>
         </input>
         <output>
            <osci:container signatureLevel="advanced"
                            encrypted="true"
                            name="XBAU_DATA"
                            required="true">
               <osci:readerRef ref="Inhaltsdaten-Verschlüsselungszertifikat"/>
               <osci:part>
                  <osci:content part="tns:response"/>
               </osci:part>
            </osci:container>
            <osci:container signatureLevel="none" encrypted="false" required="false">
               <osci:part>
                  <osci:content part="tns:optionaleNachricht"/>
               </osci:part>
            </osci:container>
         </output>
         <fault name="faultMessage">
            <osci:container signatureLevel="advanced"
                            encrypted="true"
                            name="XBAU_DATA"
                            required="true">
               <osci:readerRef ref="Inhaltsdaten-Verschlüsselungszertifikat"/>
               <osci:part>
                  <osci:content part="tns:fault"/>
               </osci:part>
            </osci:container>
            <osci:container signatureLevel="none" encrypted="false" required="false">
               <osci:part>
                  <osci:content part="tns:optionaleNachricht"/>
               </osci:part>
            </osci:container>
         </fault>
      </operation>
   </binding>
   <service name="osciABK-BAB2AIKsyncService"><!-- OSCI Infrastrukturserver -->
      <osci:devices>
         <osci:intermediary uri="" name="InternetIntermediär">
            <osci:signatureCertificate>
               <tpl:certificate/>
            </osci:signatureCertificate>
            <osci:cipherCertificate>
               <tpl:certificate/>
            </osci:cipherCertificate>
         </osci:intermediary>
         <osci:intermediary uri="" name="TESTAIntermediär">
            <osci:signatureCertificate>
               <tpl:certificate/>
            </osci:signatureCertificate>
            <osci:cipherCertificate>
               <tpl:certificate/>
            </osci:cipherCertificate>
         </osci:intermediary>
         <osci:addressee name="InternetEmpfänger">
            <osci:cipherCertificate>
               <tpl:certificate/>
            </osci:cipherCertificate>
         </osci:addressee>
         <osci:addressee name="TESTAEmpfänger">
            <osci:cipherCertificate>
               <tpl:certificate/>
            </osci:cipherCertificate>
         </osci:addressee>
      </osci:devices>
      <!-- Endpunkt im Internet -->
      <port name="osciABK-BAB2AIKsyncInternetPort" binding="tns:osciBinding">
         <documentation>
            <tpl:use>required</tpl:use> Dieser Port ist nicht optional </documentation>
         <osci:address>
            <osci:intermediaryRef ref="InternetIntermediär"/>
            <osci:addresseeRef ref="InternetEmpfänger"/>
         </osci:address>
      </port>
      <!-- Endpunkt im TESTA -->
      <port name="osciABK-BAB2AIKsyncTestaPort" binding="tns:osciBinding">
         <documentation>
            <tpl:use>optional</tpl:use> Dieser Port ist optional </documentation>
         <osci:address>
            <osci:intermediaryRef ref="TESTAIntermediär"/>
            <osci:addresseeRef ref="TESTAEmpfänger"/>
         </osci:address>
      </port>
   </service>
</definitions>
