<?xml version="1.0" encoding="UTF-8"?>
<!-- Service -->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:osci="http://www.osci.de/2006/07/wsdl/" xmlns:tpl="http://www.dvdv.de/dvdv/template/" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:tns="http://www.xleitstelle.de/xbau/2/3/XBau23-AKE-BAB2AG.wsdl" xmlns:xbau="http://www.xleitstelle.de/xbau/2/3" name="XBau23-AKE-BAB2AG" targetNamespace="http://www.xleitstelle.de/xbau/2/3/XBau23-AKE-BAB2AG.wsdl" xsi:schemaLocation="http://schemas.xmlsoap.org/wsdl/ http://schemas.xmlsoap.org/wsdl/">
	<import namespace="http://www.osci.de/2006/07/wsdl/" location="http://www.osci.de/wsdl-osci-binding/WSDL-OSCI-Binding_1.2.xsd"/>
	<import namespace="http://www.xleitstelle.de/xbau/2/3" location="https://www.xleitstelle.de/xbau/schema/2/3/xbau-nachrichten-akteneinsicht.xsd"/>
	<documentation><![CDATA[
	<html>
	<body><h1>Datenübermittlungen der Bauaufsichtsbehörden im Rahmen des Verfahrens der Akteneinsicht an die Amtsgerichte</h1>
	<p>
		Folgende Nachrichten des XBau-Schemas sind als Input der Operation <i>sendeAKE-BAB2AG</i> zulässig:
		<ul>
			<ul>
				<li>xbau:akteneinsicht.anforderungGrundbuchauszug.0125</li>
			</ul>
		</ul>
	</p>
	<p>
		Organisationsschlüssel für <i>find.servicedescription</i>-Anfragen sind die Behördenkennzeichen der im XRepository veröffentlichten Codeliste urn:de:bund:bfj:schluesseltabelle:justizbehoerdenkennzeichen; der zu verwendende Präfix lautet "<b>ag</b>". 
	</p>
	<p>
		Zulässige Dienstanbieter sind ausschließlich Organisationen der DVDV-Organisationskategorie "<b>Amtsgericht</b>". Zulässige Dienstnutzer sind ausschließlich Organisationen in der DVDV-Organisationskategorie "<b>Bauaufsichtsbehörde</b>".
	</p>
	</body>
	</html>]]></documentation>
	<message name="ake-bab2agNachricht">
		<part name="ake-bab2agNachricht" element="xbau:akteneinsicht.anforderungGrundbuchauszug.0125"/>
		<part name="optionaleNachricht" type="xs:anyType"/>
	</message>
	<portType name="osciAKE-BAB2AGInterface">
		<operation name="sendeAKE-BAB2AG">
			<input message="tns:ake-bab2agNachricht"/>
		</operation>
	</portType>
	<binding name="osciBinding" type="tns:osciAKE-BAB2AGInterface">
		<osci:binding signatureLevel="none" encrypted="true">
			<osci:reader name="Inhaltsdaten-Verschlüsselungszertifikat">
				<tpl:certificate/>
			</osci:reader>
		</osci:binding>
		<!-- Vorbelegung der Richtlinien zur Signatur und Verschlüsselung der Nutzdaten für alle Operationen -->
		<operation name="sendeAKE-BAB2AG">
			<osci:operation communicationType="one-way-active" subject="XBAU_DATA"/>
			<input>
				<osci:container required="true" signatureLevel="advanced" encrypted="true" name="XBAU_DATA">
					<osci:readerRef ref="Inhaltsdaten-Verschlüsselungszertifikat"/>
					<osci:part>
						<osci:content part="tns:ake-bab2agNachricht"/>
					</osci:part>
				</osci:container>
				<osci:container required="false" signatureLevel="none" encrypted="false">
					<osci:part>
						<osci:content part="tns:optionaleNachricht"/>
					</osci:part>
				</osci:container>
			</input>
		</operation>
	</binding>
	<service name="osciAKE-BAB2AGService">
		<!-- OSCI Infrastrukturserver -->
		<osci:devices>
			<osci:intermediary uri="" name="InternetIntermediär">
				<osci:signatureCertificate>
					<tpl:certificate/>
				</osci:signatureCertificate>
				<osci:cipherCertificate>
					<tpl:certificate/>
				</osci:cipherCertificate>
			</osci:intermediary>
			<osci:intermediary uri="" name="TESTAIntermediär">
				<osci:signatureCertificate>
					<tpl:certificate/>
				</osci:signatureCertificate>
				<osci:cipherCertificate>
					<tpl:certificate/>
				</osci:cipherCertificate>
			</osci:intermediary>
			<osci:addressee name="InternetEmpfänger">
				<osci:cipherCertificate>
					<tpl:certificate/>
				</osci:cipherCertificate>
			</osci:addressee>
			<osci:addressee name="TESTAEmpfänger">
				<osci:cipherCertificate>
					<tpl:certificate/>
				</osci:cipherCertificate>
			</osci:addressee>
		</osci:devices>
		<!-- Endpunkt im Internet -->
		<port name="osciAKE-BAB2AGInternetPort" binding="tns:osciBinding">
			<documentation>
				<tpl:use>required</tpl:use> Dieser Port ist nicht optional </documentation>
			<osci:address>
				<osci:intermediaryRef ref="InternetIntermediär"/>
				<osci:addresseeRef ref="InternetEmpfänger"/>
			</osci:address>
		</port>
		<!-- Endpunkt im TESTA -->
		<port name="osciAKE-BAB2AGTestaPort" binding="tns:osciBinding">
			<documentation>
				<tpl:use>optional</tpl:use> Dieser Port ist optional </documentation>
			<osci:address>
				<osci:intermediaryRef ref="TESTAIntermediär"/>
				<osci:addresseeRef ref="TESTAEmpfänger"/>
			</osci:address>
		</port>
	</service>
</definitions>
