name: Schedule

on:
  # allow to manual run the action
  workflow_dispatch: {}
  schedule:
    # Run early in the morning every work day
    - cron: '30 3 * * 1-5'

jobs:
  check:
    name: 'Check for changes'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: 'Use Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: npm build and test
        run: |
          npm run clean
          npm run build
          node dist/cli.js update xbau
          node dist/cli.js update xbau-kernmodul

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - '**'

      # push the change if exists
      - name: Create Pull Request
        id: pull-request
        if: steps.changes.outputs.src == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'chore: Update in Xbau Standard'
